services:

  nginx:
    restart: always
    image: ghcr.io/mlinsightlab/mlinsightlab-nginx:latest
    depends_on:
      - jupyter
      - mlflow
      - mlil-ui
      - api-hub
    environment:
      - USE_SSL=false
    ports:
      - "80:80"
    command: /bin/sh -c "echo 'Sleeping to allow for other services to start' && sleep 60 && bash /code/setup.sh"
    deploy:
      restart_policy:
        condition: any
    networks:
      - s3_external_network
      - apihub_network
      - jupyter_network
      - mlflow_network
